version: "3"
services:
  consul:
    image: "hashicorp/consul"
    ports:
      - 8500:8500
    volumes:
      # 将当前目录下的 consul.json 挂载到容器的 /consul/config/consul.json
      - ./consul.json:/consul/config/consul.json
    #command: "agent -dev"
  mysql:
    image: "mysql:latest"
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
